// Deterministic scripted output per payload id. No real command runtime is
// available on the Cloudflare Worker backend, so the "execution" is a
// pre-authored sequence of terminal lines streamed with realistic pacing.

export type OutputLevel = "info" | "success" | "error" | "warn" | "cmd";

export type PayloadStep = {
  line: (target: string) => string;
  level: OutputLevel;
  delayMs: number;
};

export type PayloadDef = {
  id: string;
  label: string;
  description: string;
  steps: PayloadStep[];
};

const line = (
  text: string | ((t: string) => string),
  level: OutputLevel,
  delayMs: number,
): PayloadStep => ({
  line: typeof text === "string" ? () => text : text,
  level,
  delayMs,
});

export const PAYLOADS: PayloadDef[] = [
  {
    id: "recon.portscan",
    label: "recon.portscan",
    description: "TCP SYN sweep against common service ports (1-1024).",
    steps: [
      line((t) => `$ reaper exec recon.portscan --target ${t}`, "cmd", 60),
      line("[+] Initializing SYN scanner (workers=32)", "info", 120),
      line((t) => `[+] Resolving ${t} ...`, "info", 180),
      line((t) => `[+] Host ${t} appears up (rtt 14ms)`, "success", 220),
      line("[+] Sweeping ports 1-1024 ...", "info", 260),
      line("  22/tcp   open   ssh        OpenSSH 9.2p1", "success", 240),
      line("  80/tcp   open   http       nginx 1.24.0", "success", 220),
      line("  443/tcp  open   https      nginx 1.24.0 (TLS 1.3)", "success", 220),
      line("  3306/tcp filtered mysql", "warn", 260),
      line("  6379/tcp open   redis      Redis 7.0.11", "success", 220),
      line("[+] 1019 ports closed, 4 open, 1 filtered", "info", 260),
      line("[✓] recon.portscan complete", "success", 200),
    ],
  },
  {
    id: "recon.dnsenum",
    label: "recon.dnsenum",
    description: "Enumerate DNS records and common subdomains.",
    steps: [
      line((t) => `$ reaper exec recon.dnsenum --target ${t}`, "cmd", 60),
      line((t) => `[+] Querying authoritative NS for ${t}`, "info", 200),
      line("  ns1.reaper-dns.net", "info", 140),
      line("  ns2.reaper-dns.net", "info", 140),
      line("[+] Enumerating record types ...", "info", 200),
      line((t) => `  A     ${t} -> 203.0.113.42`, "success", 180),
      line((t) => `  AAAA  ${t} -> 2001:db8::2a`, "success", 180),
      line((t) => `  MX    10 mail.${t}`, "success", 200),
      line("[+] Bruteforcing 512 common subdomains ...", "info", 220),
      line((t) => `  api.${t}     -> 203.0.113.51`, "success", 200),
      line((t) => `  vpn.${t}     -> 198.51.100.12`, "success", 200),
      line((t) => `  staging.${t} -> 10.0.0.7 (RFC1918 leak)`, "warn", 220),
      line("[✓] recon.dnsenum complete", "success", 200),
    ],
  },
  {
    id: "web.headers",
    label: "web.headers",
    description: "Fetch and grade HTTP security headers.",
    steps: [
      line((t) => `$ reaper exec web.headers --target ${t}`, "cmd", 60),
      line((t) => `[+] GET https://${t}/`, "info", 180),
      line("[+] 200 OK  (server=nginx, 412ms)", "success", 200),
      line("[+] Header audit:", "info", 160),
      line("  Strict-Transport-Security  ...... PASS", "success", 160),
      line("  Content-Security-Policy    ...... MISSING", "error", 200),
      line("  X-Frame-Options            ...... PASS", "success", 160),
      line("  X-Content-Type-Options     ...... PASS", "success", 160),
      line("  Referrer-Policy            ...... WEAK (no-referrer-when-downgrade)", "warn", 200),
      line("  Permissions-Policy         ...... MISSING", "error", 200),
      line("[!] Grade: C  (2 missing, 1 weak)", "warn", 220),
      line("[✓] web.headers complete", "success", 200),
    ],
  },
  {
    id: "tls.probe",
    label: "tls.probe",
    description: "Enumerate TLS versions, ciphers, and certificate chain.",
    steps: [
      line((t) => `$ reaper exec tls.probe --target ${t}`, "cmd", 60),
      line((t) => `[+] Connecting to ${t}:443`, "info", 200),
      line("[+] Negotiated TLS 1.3 / TLS_AES_256_GCM_SHA384", "success", 220),
      line("[+] Supported protocols:", "info", 160),
      line("  TLS 1.3   ENABLED", "success", 160),
      line("  TLS 1.2   ENABLED", "success", 160),
      line("  TLS 1.1   disabled", "info", 160),
      line("  TLS 1.0   disabled", "info", 160),
      line("[+] Certificate chain:", "info", 200),
      line((t) => `  CN=${t}  issuer=R3 (Let's Encrypt)`, "success", 200),
      line("  valid: 62 days remaining", "success", 200),
      line("  SAN entries: 4", "info", 160),
      line("[✓] tls.probe complete", "success", 200),
    ],
  },
  {
    id: "auth.bruteforce",
    label: "auth.bruteforce",
    description: "Rate-limited credential test against SSH (safe mode).",
    steps: [
      line((t) => `$ reaper exec auth.bruteforce --target ${t} --mode safe`, "cmd", 60),
      line("[+] Safe mode: max 8 attempts, 400ms backoff", "info", 200),
      line((t) => `[+] Target: ssh://${t}:22`, "info", 180),
      line("  admin:admin        -> denied", "info", 260),
      line("  admin:password     -> denied", "info", 260),
      line("  root:toor          -> denied", "info", 260),
      line("  root:root          -> denied", "info", 260),
      line("  ubuntu:ubuntu      -> denied", "info", 260),
      line("  ec2-user:changeme  -> denied", "info", 260),
      line("[!] Account lockout signal detected at attempt 7", "warn", 260),
      line("[!] Aborting to avoid disruption", "warn", 220),
      line("[✓] auth.bruteforce halted (safe)", "success", 200),
    ],
  },
  {
    id: "recon.portscan.full",
    label: "recon.portscan.full",
    description: "Scan common service ports across the standard attack surface.",
    steps: [
      line((t) => `$ reaper exec recon.portscan.full --target ${t}`, "cmd", 60),
      line((t) => `[→] Resolving ${t} ...`, "info", 180),
      line((t) => `[+] Host ${t} up (rtt 12ms)`, "success", 200),
      line("[→] Scanning 19 common ports ...", "info", 200),
      line("  [✓]   21/tcp   open      ftp        vsftpd 3.0.3", "success", 180),
      line("  [✓]   22/tcp   open      ssh        OpenSSH 9.2p1", "success", 160),
      line("  [✗]   23/tcp   filtered  telnet", "warn", 160),
      line("  [·]   25/tcp   closed    smtp", "info", 140),
      line("  [✓]   53/tcp   open      domain     BIND 9.18", "success", 160),
      line("  [✓]   80/tcp   open      http       nginx 1.24.0", "success", 160),
      line("  [·]  110/tcp   closed    pop3", "info", 140),
      line("  [✗]  135/tcp   filtered  msrpc", "warn", 160),
      line("  [✗]  139/tcp   filtered  netbios-ssn", "warn", 160),
      line("  [·]  143/tcp   closed    imap", "info", 140),
      line("  [✓]  443/tcp   open      https      nginx 1.24.0 (TLS 1.3)", "success", 180),
      line("  [✗]  445/tcp   filtered  microsoft-ds", "warn", 160),
      line("  [·]  993/tcp   closed    imaps", "info", 140),
      line("  [·]  995/tcp   closed    pop3s", "info", 140),
      line("  [·] 1723/tcp   closed    pptp", "info", 140),
      line("  [✓] 3306/tcp   open      mysql      MySQL 8.0.34", "success", 180),
      line("  [✗] 3389/tcp   filtered  ms-wbt-server", "warn", 160),
      line("  [·] 5900/tcp   closed    vnc", "info", 140),
      line("  [✓] 8080/tcp   open      http-proxy nginx", "success", 180),
      line("[+] 7 open · 6 closed · 6 filtered", "info", 220),
      line("[✓] recon.portscan.full complete", "success", 200),
    ],
  },
  {
    id: "recon.subdomain",
    label: "recon.subdomain",
    description: "Bruteforce a common subdomain wordlist and resolve results.",
    steps: [
      line((t) => `$ reaper exec recon.subdomain --target ${t}`, "cmd", 60),
      line("[+] Wordlist: common-10 (www, mail, ftp, dev, api, admin, test, staging, beta, docs)", "info", 200),
      line((t) => `[→] Testing www.${t} ...`, "info", 220),
      line((t) => `  [✓] www.${t}     → 203.0.113.42`, "success", 200),
      line((t) => `[→] Testing mail.${t} ...`, "info", 200),
      line((t) => `  [✓] mail.${t}    → 203.0.113.51 (MX)`, "success", 200),
      line((t) => `[→] Testing ftp.${t} ...`, "info", 180),
      line((t) => `  [·] ftp.${t}     → NXDOMAIN`, "info", 180),
      line((t) => `[→] Testing dev.${t} ...`, "info", 200),
      line((t) => `  [✓] dev.${t}     → 10.0.0.14 (RFC1918 leak)`, "warn", 220),
      line((t) => `[→] Testing api.${t} ...`, "info", 200),
      line((t) => `  [✓] api.${t}     → 203.0.113.77`, "success", 200),
      line((t) => `[→] Testing admin.${t} ...`, "info", 200),
      line((t) => `  [✓] admin.${t}   → 198.51.100.9 (exposed)`, "warn", 220),
      line((t) => `[→] Testing test.${t} ...`, "info", 180),
      line((t) => `  [·] test.${t}    → NXDOMAIN`, "info", 160),
      line((t) => `[→] Testing staging.${t} ...`, "info", 200),
      line((t) => `  [✓] staging.${t} → 10.0.0.22 (RFC1918 leak)`, "warn", 220),
      line((t) => `[→] Testing beta.${t} ...`, "info", 180),
      line((t) => `  [·] beta.${t}    → NXDOMAIN`, "info", 160),
      line((t) => `[→] Testing docs.${t} ...`, "info", 200),
      line((t) => `  [✓] docs.${t}    → 203.0.113.90`, "success", 200),
      line("[+] 6 subdomains resolved · 3 NXDOMAIN · 3 flagged", "info", 220),
      line("[✓] recon.subdomain complete", "success", 200),
    ],
  },
  {
    id: "recon.whois",
    label: "recon.whois",
    description: "Retrieve WHOIS registration record for the target domain.",
    steps: [
      line((t) => `$ reaper exec recon.whois --target ${t}`, "cmd", 60),
      line((t) => `[→] Querying whois.iana.org for ${t} ...`, "info", 240),
      line("[+] Referred to whois.verisign-grs.com", "info", 200),
      line("[+] Record retrieved:", "success", 200),
      line((t) => `  Domain Name:         ${t.toUpperCase()}`, "info", 160),
      line("  Registrar:           MarkMonitor Inc.", "info", 160),
      line("  Registrar IANA ID:   292", "info", 140),
      line("  Created:             2004-03-15T00:00:00Z", "info", 160),
      line("  Updated:             2025-02-11T09:22:14Z", "info", 160),
      line("  Expires:             2027-03-15T00:00:00Z", "info", 160),
      line("  Status:              clientTransferProhibited", "info", 160),
      line("  Status:              clientUpdateProhibited", "info", 160),
      line("  Name Server:         NS1.MARKMONITOR.COM", "success", 160),
      line("  Name Server:         NS2.MARKMONITOR.COM", "success", 160),
      line("  DNSSEC:              signedDelegation", "success", 180),
      line("  Registrant Org:      REDACTED FOR PRIVACY", "warn", 180),
      line("[✓] recon.whois complete", "success", 200),
    ],
  },
  {
    id: "tls.scan",
    label: "tls.scan",
    description: "Enumerate TLS versions, cipher suites, and certificate metadata.",
    steps: [
      line((t) => `$ reaper exec tls.scan --target ${t}`, "cmd", 60),
      line((t) => `[→] Connecting to ${t}:443 ...`, "info", 220),
      line("[+] Handshake OK · negotiated TLS 1.3", "success", 220),
      line("[→] Enumerating protocol support ...", "info", 200),
      line("  [✓] TLS 1.3     ENABLED", "success", 160),
      line("  [✓] TLS 1.2     ENABLED", "success", 160),
      line("  [·] TLS 1.1     disabled", "info", 140),
      line("  [·] TLS 1.0     disabled", "info", 140),
      line("  [·] SSLv3       disabled", "info", 140),
      line("[→] Enumerating cipher suites ...", "info", 220),
      line("  [✓] TLS_AES_256_GCM_SHA384         (strong)", "success", 160),
      line("  [✓] TLS_CHACHA20_POLY1305_SHA256   (strong)", "success", 160),
      line("  [✓] ECDHE-RSA-AES256-GCM-SHA384    (strong)", "success", 160),
      line("  [!] ECDHE-RSA-AES128-SHA           (weak: SHA1 MAC)", "warn", 200),
      line("  [!] DHE-RSA-AES256-SHA             (weak: SHA1 MAC)", "warn", 200),
      line("[→] Fetching certificate chain ...", "info", 200),
      line((t) => `  CN=${t}   issuer=R3 (Let's Encrypt)`, "success", 200),
      line("  valid:   62 days remaining", "success", 160),
      line("  SAN:     4 entries", "info", 160),
      line("[!] Grade: B  (2 weak cipher suites)", "warn", 220),
      line("[✓] tls.scan complete", "success", 200),
    ],
  },
  {
    id: "web.dirbrute",
    label: "web.dirbrute",
    description: "Bruteforce common web paths and report HTTP status codes.",
    steps: [
      line((t) => `$ reaper exec web.dirbrute --target ${t}`, "cmd", 60),
      line("[+] Wordlist: common-paths-8", "info", 180),
      line((t) => `[→] GET https://${t}/admin`, "info", 200),
      line("  [✓] 200 /admin              (2.1kb)", "success", 180),
      line((t) => `[→] GET https://${t}/login`, "info", 200),
      line("  [✓] 200 /login              (1.4kb)", "success", 180),
      line((t) => `[→] GET https://${t}/wp-admin`, "info", 200),
      line("  [·] 404 /wp-admin", "info", 160),
      line((t) => `[→] GET https://${t}/api`, "info", 200),
      line("  [✓] 401 /api                (auth required)", "warn", 200),
      line((t) => `[→] GET https://${t}/backup`, "info", 200),
      line("  [✓] 403 /backup             (dir listing denied)", "warn", 200),
      line((t) => `[→] GET https://${t}/config`, "info", 200),
      line("  [·] 404 /config", "info", 160),
      line((t) => `[→] GET https://${t}/.git`, "info", 220),
      line("  [!] 200 /.git/HEAD          (repo exposed!)", "error", 240),
      line((t) => `[→] GET https://${t}/.env`, "info", 220),
      line("  [!] 200 /.env               (secrets exposed!)", "error", 240),
      line("[+] 6 hits · 2 critical exposures", "warn", 220),
      line("[✓] web.dirbrute complete", "success", 200),
    ],
  },
  {
    id: "recon.dnsrecords",
    label: "recon.dnsrecords",
    description: "Query MX, NS, TXT, and CNAME records for the target domain.",
    steps: [
      line((t) => `$ reaper exec recon.dnsrecords --target ${t}`, "cmd", 60),
      line((t) => `[→] Querying A / AAAA for ${t} ...`, "info", 200),
      line((t) => `  A       ${t}   → 203.0.113.42`, "success", 180),
      line((t) => `  AAAA    ${t}   → 2001:db8::2a`, "success", 180),
      line("[→] Querying MX ...", "info", 200),
      line((t) => `  MX      10 mail1.${t}`, "success", 180),
      line((t) => `  MX      20 mail2.${t}`, "success", 180),
      line("[→] Querying NS ...", "info", 200),
      line("  NS      ns1.reaper-dns.net", "success", 180),
      line("  NS      ns2.reaper-dns.net", "success", 180),
      line("[→] Querying TXT ...", "info", 200),
      line("  TXT     \"v=spf1 include:_spf.google.com ~all\"", "success", 200),
      line("  TXT     \"google-site-verification=Ab12Cd34...\"", "info", 180),
      line("  TXT     \"MS=ms84920184\"", "info", 160),
      line("[→] Querying CNAME ...", "info", 200),
      line((t) => `  CNAME   www.${t}    → ${t}`, "success", 180),
      line((t) => `  CNAME   cdn.${t}    → d1abcxyz.cloudfront.net`, "success", 200),
      line("[+] 11 records enumerated across 5 types", "info", 220),
      line("[✓] recon.dnsrecords complete", "success", 200),
    ],
  },
  {
    id: "recon.cloud",
    label: "recon.cloud",
    description: "Fingerprint the hosting cloud provider from network signals.",
    steps: [
      line((t) => `$ reaper exec recon.cloud --target ${t}`, "cmd", 60),
      line((t) => `[→] Resolving ${t} ...`, "info", 200),
      line("[+] Primary A record → 52.84.203.11", "success", 200),
      line("[→] Reverse DNS lookup ...", "info", 220),
      line("  PTR → server-52-84-203-11.iad79.r.cloudfront.net", "success", 220),
      line("[→] Cross-referencing published IP ranges ...", "info", 240),
      line("  [·] AWS EC2 range          no match", "info", 160),
      line("  [✓] AWS CloudFront range   MATCH (52.84.0.0/15)", "success", 200),
      line("  [·] GCP compute range      no match", "info", 160),
      line("  [·] Azure range            no match", "info", 160),
      line("  [·] DigitalOcean range     no match", "info", 160),
      line("  [·] Cloudflare range       no match", "info", 160),
      line("[→] Inspecting response headers ...", "info", 220),
      line("  Server: CloudFront", "success", 180),
      line("  X-Amz-Cf-Pop: IAD79-C1", "success", 180),
      line("[+] Provider: AWS (CloudFront edge)   confidence 98%", "success", 240),
      line("[✓] recon.cloud complete", "success", 200),
    ],
  },
  {
    id: "vuln.cvelookup",
    label: "vuln.cvelookup",
    description: "Cross-reference detected service banners against the CVE feed.",
    steps: [
      line((t) => `$ reaper exec vuln.cvelookup --target ${t}`, "cmd", 60),
      line("[+] Loading service fingerprints from last scan ...", "info", 200),
      line("  · nginx 1.24.0", "info", 160),
      line("  · OpenSSH 9.2p1", "info", 160),
      line("  · MySQL 8.0.34", "info", 160),
      line("[→] Querying NVD feed ...", "info", 240),
      line("[→] Checking CVE-2023-44487 (HTTP/2 Rapid Reset) ...", "info", 260),
      line("  [!] CVE-2023-44487   HIGH      CVSS 7.5   nginx <1.25.3   AFFECTED", "error", 260),
      line("[→] Checking CVE-2023-38408 (ssh-agent RCE) ...", "info", 240),
      line("  [·] CVE-2023-38408   HIGH      CVSS 9.8   OpenSSH <9.3p2  patched", "success", 220),
      line("[→] Checking CVE-2024-6387 (regreSSHion) ...", "info", 240),
      line("  [!] CVE-2024-6387    CRITICAL  CVSS 8.1   OpenSSH 8.5-9.7 AFFECTED", "error", 260),
      line("[→] Checking CVE-2023-21980 (MySQL Server) ...", "info", 240),
      line("  [·] CVE-2023-21980   MEDIUM    CVSS 4.9   MySQL <8.0.33   patched", "success", 220),
      line("[→] Checking CVE-2021-44228 (Log4Shell) ...", "info", 240),
      line("  [·] CVE-2021-44228   CRITICAL  CVSS 10.0  n/a (no Java stack detected)", "info", 200),
      line("[!] 2 exploitable CVEs · 1 CRITICAL · 1 HIGH", "error", 260),
      line("[✓] vuln.cvelookup complete", "success", 200),
    ],
  },
  {
    id: "web.headers.audit",
    label: "web.headers.audit",
    description: "Audit HTTP security headers and recommend remediation.",
    steps: [
      line((t) => `$ reaper exec web.headers.audit --target ${t}`, "cmd", 60),
      line((t) => `[→] GET https://${t}/ ...`, "info", 200),
      line("[+] 200 OK  server=nginx (412ms)", "success", 200),
      line("[→] Auditing security headers ...", "info", 200),
      line("  [✓] Strict-Transport-Security   present  (max-age=63072000; includeSubDomains)", "success", 180),
      line("  [✗] Content-Security-Policy     MISSING  → set default-src 'self'", "error", 220),
      line("  [✓] X-Frame-Options             present  (SAMEORIGIN)", "success", 180),
      line("  [✓] X-Content-Type-Options      present  (nosniff)", "success", 180),
      line("  [!] Referrer-Policy             WEAK     (no-referrer-when-downgrade) → use strict-origin-when-cross-origin", "warn", 220),
      line("  [✗] Permissions-Policy          MISSING  → restrict camera/geolocation/microphone", "error", 220),
      line("  [✓] Cross-Origin-Opener-Policy  present  (same-origin)", "success", 180),
      line("  [!] X-XSS-Protection            LEGACY   → remove; superseded by CSP", "warn", 200),
      line("[!] Grade: C   2 missing · 2 weak", "warn", 240),
      line("[✓] web.headers.audit complete", "success", 200),
    ],
  },
  {
    id: "web.techstack",
    label: "web.techstack",
    description: "Fingerprint frameworks, CMS, and JavaScript libraries in use.",
    steps: [
      line((t) => `$ reaper exec web.techstack --target ${t}`, "cmd", 60),
      line((t) => `[→] Fetching https://${t}/ ...`, "info", 220),
      line("[+] 200 OK · 214kb · 87 assets referenced", "success", 220),
      line("[→] Parsing response headers ...", "info", 200),
      line("  [✓] Server            nginx 1.24.0", "success", 180),
      line("  [✓] X-Powered-By      Next.js", "success", 200),
      line("[→] Parsing HTML meta ...", "info", 200),
      line("  [✓] generator         Next.js 14.2.5", "success", 200),
      line("  [✓] CMS               (none detected — headless)", "info", 180),
      line("[→] Scanning script tags ...", "info", 220),
      line("  [✓] React 18.3.1                    /static/chunks/react.js", "success", 200),
      line("  [✓] Next.js router 14.2.5           /_next/static/chunks/main.js", "success", 200),
      line("  [✓] TanStack Query 5.32.0           /_next/static/chunks/query.js", "success", 200),
      line("  [✓] Tailwind CSS 3.4.4              inline utility classes", "success", 200),
      line("  [✓] Recharts 2.12.7                 /_next/static/chunks/charts.js", "success", 200),
      line("  [✓] Sentry Browser 8.9.2            /_next/static/chunks/sentry.js", "success", 200),
      line("[→] Detecting analytics ...", "info", 200),
      line("  [✓] Vercel Analytics                script src=/_vercel/insights/script.js", "success", 200),
      line("[+] Stack: Next.js · React · Tailwind · Recharts   host: Vercel", "success", 240),
      line("[✓] web.techstack complete", "success", 200),
    ],
  },
];

export const PAYLOAD_MAP = Object.fromEntries(PAYLOADS.map((p) => [p.id, p]));
